### ISSUE TITLE
Deployment fails because of Chinese Translation

### ISSUE THREAD

**Issue by phil-opp** [dora-rs/dora-rs.github.io#14]
The following error occurs during deployment: https://github.com/dora-rs/dora-rs.github.io/actions/runs/8582971914/job/23573223797

```
Error: MDX compilation failed for file "/home/runner/work/dora-rs.github.io/dora-rs.github.io/i18n/zh-CN/docusaurus-plugin-content-docs/current/guides/dora-drives/obstacle_location.mdx"
Cause: Unexpected character `/` (U+002F) before local name, expected a character that can start a name, such as a letter, `$`, or `_` (note: to create a link in MDX, use `[text](url)`)
```

Seems related to the recent translation changes to `obstacle_location.mdx` on https://crowdin.com/project/dora-rs/activity-stream .

**Comment by haixuanTao** [comment]
Sure thing, I'm pushing a fix

**Comment by haixuanTao** [comment]
Deployment is fixed. There were a weird build from crowdin: https://github.com/dora-rs/dora-rs.github.io/actions/runs/8605160589

**Comment by phil-opp** [comment]
Thanks!
