### ISSUE TITLE
Deploy fails on `main`

### ISSUE THREAD

**Issue by phil-opp** [dora-rs/dora-rs.github.io#9]
After merging #8, the deploy job fails in the "Build website" step. I don't think that the PR is related as it's just a basic typo fix. Maybe some dependency was updated?

The error message is:

```

SyntaxError: /home/runner/work/dora-rs.github.io/dora-rs.github.io/i18n/zh-CN/docusaurus-plugin-content-docs/current/guides/Installation/uninstalling.mdx: Expected corresponding JSX closing tag for <MDXLayout>. (12:2)
  10 | <pre><code parentName="pre" {...{"className":"language-bash"}}>{`pip uninstall dora-rs
  11 | `}</code></pre>
> 12 |   </TabItem>
     |   ^
  13 | </Tabs>
  14 | <h2 {...{"id":"cargo与提示"}}>{`Cargo与提示`}</h2>
  15 | <pre><code parentName="pre" {...{"className":"language-bash"}}>{`cargo remove dora-cli
Error:  Client bundle compiled with errors therefore further build is impossible.
```

See https://github.com/dora-rs/dora-rs.github.io/actions/runs/7144345617/job/19457742017 for the full build output.

**Comment by haixuanTao** [comment]
It seems to be an issue with the chinese translations that has removed opening tags from the initial text. I have removed the translation in question. The problem is fixed

**Comment by haixuanTao** [comment]
A good part of the website has now been translated: https://dora.carsmos.ai/zh-CN/ :)

**Comment by phil-opp** [comment]
Thanks!
